package response

type Place struct {
	Name                         string               `json:"name"`
	ID                           string               `json:"id"`
	DisplayName                  LocalizedText        `json:"displayName"`
	Types                        []string             `json:"types"`
	PrimaryType                  string               `json:"primaryType"`
	PrimaryTypeDisplayName       LocalizedText        `json:"primaryTypeDisplayName"`
	NationalPhoneNumber          string               `json:"nationalPhoneNumber"`
	InternationalPhoneNumber     string               `json:"internationalPhoneNumber"`
	FormattedAddress             string               `json:"formattedAddress"`
	ShortFormattedAddress        string               `json:"shortFormattedAddress"`
	AddressComponents            []AddressComponent   `json:"addressComponents"`
	PlusCode                     PlusCode             `json:"plusCode"`
	Location                     LatLng               `json:"location"`
	Viewport                     Viewport             `json:"viewport"`
	Rating                       float64              `json:"rating"`
	GoogleMapsUri                string               `json:"googleMapsUri"`
	WebsiteUri                   string               `json:"websiteUri"`
	Reviews                      []Review             `json:"reviews"`
	RegularOpeningHours          OpeningHours         `json:"regularOpeningHours"`
	Photos                       []Photo              `json:"photos"`
	AdrFormatAddress             string               `json:"adrFormatAddress"`
	BusinessStatus               string               `json:"businessStatus"`
	PriceLevel                   string               `json:"priceLevel"`
	Attributions                 []Attribution        `json:"attributions"`
	IconMaskBaseUri              string               `json:"iconMaskBaseUri"`
	IconBackgroundColor          string               `json:"iconBackgroundColor"`
	CurrentOpeningHours          OpeningHours         `json:"currentOpeningHours"`
	CurrentSecondaryOpeningHours []OpeningHours       `json:"currentSecondaryOpeningHours"`
	RegularSecondaryOpeningHours []OpeningHours       `json:"regularSecondaryOpeningHours"`
	EditorialSummary             LocalizedText        `json:"editorialSummary"`
	PaymentOptions               PaymentOptions       `json:"paymentOptions"`
	ParkingOptions               ParkingOptions       `json:"parkingOptions"`
	SubDestinations              []SubDestination     `json:"subDestinations"`
	FuelOptions                  FuelOptions          `json:"fuelOptions"`
	EVChargeOptions              EVChargeOptions      `json:"evChargeOptions"`
	GenerativeSummary            GenerativeSummary    `json:"generativeSummary"`
	AreaSummary                  AreaSummary          `json:"areaSummary"`
	ContainingPlaces             []ContainingPlace    `json:"containingPlaces"`
	AddressDescriptor            AddressDescriptor    `json:"addressDescriptor"`
	GoogleMapsLinks              GoogleMapsLinks      `json:"googleMapsLinks"`
	PriceRange                   PriceRange           `json:"priceRange"`
	UtcOffsetMinutes             int                  `json:"utcOffsetMinutes"`
	UserRatingCount              int                  `json:"userRatingCount"`
	Takeout                      bool                 `json:"takeout"`
	Delivery                     bool                 `json:"delivery"`
	DineIn                       bool                 `json:"dineIn"`
	CurbsidePickup               bool                 `json:"curbsidePickup"`
	Reservable                   bool                 `json:"reservable"`
	ServesBreakfast              bool                 `json:"servesBreakfast"`
	ServesLunch                  bool                 `json:"servesLunch"`
	ServesDinner                 bool                 `json:"servesDinner"`
	ServesBeer                   bool                 `json:"servesBeer"`
	ServesWine                   bool                 `json:"servesWine"`
	ServesBrunch                 bool                 `json:"servesBrunch"`
	ServesVegetarianFood         bool                 `json:"servesVegetarianFood"`
	OutdoorSeating               bool                 `json:"outdoorSeating"`
	LiveMusic                    bool                 `json:"liveMusic"`
	MenuForChildren              bool                 `json:"menuForChildren"`
	ServesCocktails              bool                 `json:"servesCocktails"`
	ServesDessert                bool                 `json:"servesDessert"`
	ServesCoffee                 bool                 `json:"servesCoffee"`
	GoodForChildren              bool                 `json:"goodForChildren"`
	AllowsDogs                   bool                 `json:"allowsDogs"`
	Restroom                     bool                 `json:"restroom"`
	GoodForGroups                bool                 `json:"goodForGroups"`
	GoodForWatchingSports        bool                 `json:"goodForWatchingSports"`
	AccessibilityOptions         AccessibilityOptions `json:"accessibilityOptions"`
	PureServiceAreaBusiness      bool                 `json:"pureServiceAreaBusiness"`
}
